<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FiscalCR.Domain\FiscalCR.Domain.csproj" />
    <ProjectReference Include="..\..\Api\Api.Application\Api.Application.csproj" />
    <ProjectReference Include="..\..\Invoicing\Invoicing.Domain\Invoicing.Domain.csproj" />
    <ProjectReference Include="..\..\Parties\Parties.Domain\Parties.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.*" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.6" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
