// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sales.Infrastructure.Persistence;

#nullable disable

namespace Sales.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SalesDbContext))]
    [Migration("20260517091703_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sales")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sales.Domain.Orders.SalesOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("OriginQuoteId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("RequestedDeliveryDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "OrderNumber")
                        .IsUnique();

                    b.ToTable("SalesOrders", "sales");
                });

            modelBuilder.Entity("Sales.Domain.Quotes.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("QuoteNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("ValidUntil")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "QuoteNumber")
                        .IsUnique();

                    b.ToTable("Quotes", "sales");
                });

            modelBuilder.Entity("Sales.Domain.Orders.SalesOrder", b =>
                {
                    b.OwnsMany("Sales.Domain.Orders.SalesOrderLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CatalogItemId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<decimal>("DiscountPercent")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("FulfilledQuantity")
                                .HasColumnType("numeric");

                            b1.Property<string>("ItemName")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)");

                            b1.Property<string>("Notes")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Quantity")
                                .HasColumnType("numeric");

                            b1.Property<string>("SKU")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("Id");

                            b1.HasIndex("OrderId");

                            b1.ToTable("SalesOrderLine", "sales");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.OwnsOne("Api.Domain.Common.Money", "LineTotal", b2 =>
                                {
                                    b2.Property<Guid>("SalesOrderLineId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric")
                                        .HasColumnName("LineTotal_Amount");

                                    b2.Property<string>("CurrencyCode")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("LineTotal_Currency");

                                    b2.HasKey("SalesOrderLineId");

                                    b2.ToTable("SalesOrderLine", "sales");

                                    b2.WithOwner()
                                        .HasForeignKey("SalesOrderLineId");
                                });

                            b1.OwnsOne("Api.Domain.Common.Money", "UnitPrice", b2 =>
                                {
                                    b2.Property<Guid>("SalesOrderLineId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric")
                                        .HasColumnName("UnitPrice_Amount");

                                    b2.Property<string>("CurrencyCode")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("UnitPrice_Currency");

                                    b2.HasKey("SalesOrderLineId");

                                    b2.ToTable("SalesOrderLine", "sales");

                                    b2.WithOwner()
                                        .HasForeignKey("SalesOrderLineId");
                                });

                            b1.Navigation("LineTotal")
                                .IsRequired();

                            b1.Navigation("UnitPrice")
                                .IsRequired();
                        });

                    b.OwnsOne("Api.Domain.Common.Money", "Subtotal", b1 =>
                        {
                            b1.Property<Guid>("SalesOrderId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("Subtotal_Amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("Subtotal_Currency");

                            b1.HasKey("SalesOrderId");

                            b1.ToTable("SalesOrders", "sales");

                            b1.WithOwner()
                                .HasForeignKey("SalesOrderId");
                        });

                    b.OwnsOne("Api.Domain.Common.Money", "TaxAmount", b1 =>
                        {
                            b1.Property<Guid>("SalesOrderId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("TaxAmount_Amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("TaxAmount_Currency");

                            b1.HasKey("SalesOrderId");

                            b1.ToTable("SalesOrders", "sales");

                            b1.WithOwner()
                                .HasForeignKey("SalesOrderId");
                        });

                    b.OwnsOne("Api.Domain.Common.Money", "Total", b1 =>
                        {
                            b1.Property<Guid>("SalesOrderId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("Total_Amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("Total_Currency");

                            b1.HasKey("SalesOrderId");

                            b1.ToTable("SalesOrders", "sales");

                            b1.WithOwner()
                                .HasForeignKey("SalesOrderId");
                        });

                    b.Navigation("Lines");

                    b.Navigation("Subtotal")
                        .IsRequired();

                    b.Navigation("TaxAmount")
                        .IsRequired();

                    b.Navigation("Total")
                        .IsRequired();
                });

            modelBuilder.Entity("Sales.Domain.Quotes.Quote", b =>
                {
                    b.OwnsOne("Api.Domain.Common.Money", "Subtotal", b1 =>
                        {
                            b1.Property<Guid>("QuoteId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("Subtotal_Amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("Subtotal_Currency");

                            b1.HasKey("QuoteId");

                            b1.ToTable("Quotes", "sales");

                            b1.WithOwner()
                                .HasForeignKey("QuoteId");
                        });

                    b.OwnsOne("Api.Domain.Common.Money", "TaxAmount", b1 =>
                        {
                            b1.Property<Guid>("QuoteId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("TaxAmount_Amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("TaxAmount_Currency");

                            b1.HasKey("QuoteId");

                            b1.ToTable("Quotes", "sales");

                            b1.WithOwner()
                                .HasForeignKey("QuoteId");
                        });

                    b.OwnsOne("Api.Domain.Common.Money", "Total", b1 =>
                        {
                            b1.Property<Guid>("QuoteId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("Total_Amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("Total_Currency");

                            b1.HasKey("QuoteId");

                            b1.ToTable("Quotes", "sales");

                            b1.WithOwner()
                                .HasForeignKey("QuoteId");
                        });

                    b.OwnsMany("Sales.Domain.Quotes.QuoteLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CatalogItemId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<decimal>("DiscountPercent")
                                .HasColumnType("numeric");

                            b1.Property<string>("ItemName")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)");

                            b1.Property<string>("Notes")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<decimal>("Quantity")
                                .HasColumnType("numeric");

                            b1.Property<Guid>("QuoteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("SKU")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("Id");

                            b1.HasIndex("QuoteId");

                            b1.ToTable("QuoteLine", "sales");

                            b1.WithOwner()
                                .HasForeignKey("QuoteId");

                            b1.OwnsOne("Api.Domain.Common.Money", "LineTotal", b2 =>
                                {
                                    b2.Property<Guid>("QuoteLineId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric")
                                        .HasColumnName("LineTotal_Amount");

                                    b2.Property<string>("CurrencyCode")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("LineTotal_Currency");

                                    b2.HasKey("QuoteLineId");

                                    b2.ToTable("QuoteLine", "sales");

                                    b2.WithOwner()
                                        .HasForeignKey("QuoteLineId");
                                });

                            b1.OwnsOne("Api.Domain.Common.Money", "UnitPrice", b2 =>
                                {
                                    b2.Property<Guid>("QuoteLineId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric")
                                        .HasColumnName("UnitPrice_Amount");

                                    b2.Property<string>("CurrencyCode")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("UnitPrice_Currency");

                                    b2.HasKey("QuoteLineId");

                                    b2.ToTable("QuoteLine", "sales");

                                    b2.WithOwner()
                                        .HasForeignKey("QuoteLineId");
                                });

                            b1.Navigation("LineTotal")
                                .IsRequired();

                            b1.Navigation("UnitPrice")
                                .IsRequired();
                        });

                    b.Navigation("Lines");

                    b.Navigation("Subtotal")
                        .IsRequired();

                    b.Navigation("TaxAmount")
                        .IsRequired();

                    b.Navigation("Total")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
