<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.5.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Api\Api.Application\Api.Application.csproj" />
    <ProjectReference Include="..\..\Accounting\Accounting.Domain\Accounting.Domain.csproj" />
    <ProjectReference Include="..\..\Inventory\Inventory.Domain\Inventory.Domain.csproj" />
    <ProjectReference Include="..\..\Purchasing\Purchasing.Domain\Purchasing.Domain.csproj" />
    <ProjectReference Include="..\..\Sales\Sales.Domain\Sales.Domain.csproj" />
    <ProjectReference Include="..\..\Banking\Banking.Domain\Banking.Domain.csproj" />
  </ItemGroup>
</Project>
