apiVersion: v1
kind: Service
metadata:
  name: bff
  namespace: demo
  labels:
    app: bff
spec:
  selector:
    app: bff
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
