apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: demo
  labels:
    app: worker
    app.kubernetes.io/component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: demo/worker:latest
          imagePullPolicy: Always
          env:
            - name: DOTNET_ENVIRONMENT
              value: Production
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.demo-monitoring.svc.cluster.local:4317"
            - name: OTEL_SERVICE_NAME
              value: demo-worker
            - name: MessageBus__Transport
              value: RabbitMQ
            - name: MessageBus__RabbitMQ__Host
              value: rabbitmq
            - name: MessageBus__RabbitMQ__Username
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: username
            - name: MessageBus__RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: password
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
